version: '3.7'

networks:
  docker_private:
    name: docker_private
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET}
        gateway: ${GATEWAY}

services:

  php-fpm:
    image: 271217/felix-php-fpm:7.4
    container_name: php-${PHP_CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    dns: ${DNS}
    networks:
      - docker_private
    volumes:
      - '../:/var/www'
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    labels:
      com.example.description: "PHP fpm server"
      

  nginx-balancer:
    image: 'nginx:1.21.6-alpine'
    container_name: nginx-${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    dns: ${DNS}
    networks:
      - docker_private
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../:/var/www'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/snipets/:/etc/nginx/conf.d/snipets/'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './logs/nginx:/var/log/nginx'
    labels:
      com.example.description: "Nginx Web server to balance PHP and static content"